### ISSUE TITLE
Sandwych.Reporting.OfficeML missing (v2.1.1)

### ISSUE THREAD

**Issue by Lydecker** [oldrev/maltreport#15]
Hi,

Just installed MaltReport2 v2.1.1 in a VS2017 project via NuGet.

When referencing Sandwych.Reporting, OfficeML is missing as shown in your example: WordMLDocumentTest.cs 

![image](https://user-images.githubusercontent.com/12632602/33024365-ce4f12ac-ce02-11e7-9b07-3e74dac7155b.png)

Any ideas?

Thanks

**Comment by oldrev** [comment]
Sorry, the example in  **dev** branch is for MaltReport 3.x, please check the **master** branch.

The 3.x will be released in one or two weeks, please stay tuned.

**Comment by oldrev** [comment]
I'm closing this issue, the 3.x version should fixed those library missing problems.
