### ISSUE TITLE
Thread deadlocking

### ISSUE THREAD

**Issue by ayaka209** [oldrev/maltreport#16]
AbstractZipDocument.cs   Line 21:
            this.OnLoadAsync(inStream).GetAwaiter().GetResult();
may lead to thread deadlock in some cases,

can be changed to
    Task.Run(()=> this.OnLoadAsync(inStream)).Wait();

to avoid problem.

**Comment by ayaka209** [comment]
public override void Save(Stream outStream) =>
            this.SaveAsync(outStream).GetAwaiter().GetResult();

should be fixed too.

**Comment by oldrev** [comment]
PR are always welcome :)

**Comment by oldrev** [comment]
Fixed by commit df67d161477cd5d3c879721ef68b4630c5408615
